
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: steve-cluster-role-test
rules:
- apiGroups: 
  - ""
  - apps
  - autoscaling
  - batch
  - extensions
  - policy
  - rbac.authorization.k8s.io
  - pods
  resources: ["*"]
  verbs: ["*"]
