apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: stevegindi # this is the namespace your service account is in
subjects:
  - kind: ServiceAccount
    name: default # Name is case sensitive
    namespace: stevegindi
    #apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: steve-cluster-role-test
  apiGroup: rbac.authorization.k8s.io
